apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy      
    spec:
      containers:
      - name: reverseproxy
        image: bom234/reverseproxy:v1
        imagePullPolicy: Always          
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "150Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"               
      restartPolicy: Always